name: Sync Fork

on:
  schedule:
  - cron: '0 0 * * 0' # every week
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync with upstream latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: master
          upstream_sync_branch: master
          upstream_sync_repo: snipe/snipe-it
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}